services:
  frontend:
    build:
      context: .
      dockerfile: Frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - portfolio-network
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}

  backend:
    build:
      context: .
      dockerfile: Backend
    networks:
      - portfolio-network
    environment:
      - HOST=${BACKEND_HOST}
      - PORT=${BACKEND_PORT}

networks:
  portfolio-network: