services:
  frontend:
    build:
      context: .
      dockerfile: Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Backend
    ports:
      - "5000:5000"