[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.13.3"
prost-build = "0.13.3"
serde_json = "1.0.132"

[build-dependencies]
prost-build = "0.13.3"
